### ISSUE TITLE
Installing dependencies

### ISSUE THREAD

**Issue by cedricleroy** [SunPower/Carousel#48]
Question: 
After installing Caroussel in a virtualenv, I notified that dependencies were not installed. Normal?

**Comment by mikofski** [comment]
I've been using [`requires` from `distutils`](https://docs.python.org/2/distutils/setupscript.html#relationships-between-distributions-and-packages) instead of [`install_requires` from `setuptools`](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-dependencies).

When I started using Python, there was no pip, only docutils and setuptools/easy_install. I remember when pip was rolled out with distribute as the new hotness and we were told to revile setuptools/easy-install, but then distribute and setuptools merged, and now things are much better. Change is good. 😸
